export const awards = [
  {
    id: 1,
    name: "Fighting Game",
    type: "2022",
    project: "View Github",
    label: "JavaScript",
    github: "https://github.com/milanlizriadi/fighting-game",
  },
  {
    id: 2,
    name: "AI ChatBot",
    type: "2023",
    project: "View Github",
    label: "HTML CSS JS",
    github: "https://github.com/milanlizriadi/TalkGPT",
  },
  {
    id: 3,
    name: "Online Code Editor",
    type: "2023",
    project: "View Github",
    label: "HTML CSS JS",
    github: "https://github.com/milanlizriadi/code-editor",
  },
  {
    id: 4,
    name: "Old Portfolio Web",
    type: "2024",
    project: "View Github",
    label: "HTML CSS JS",
    github: "https://github.com/milanlizriadi/portfolio-milan",
  },
  {
    id: 5,
    name: "Bookshelf API",
    type: "2024",
    project: "View Github",
    label: "JavaScript",
    github: "https://github.com/milanlizriadi/bookshelf-api",
  },
  {
    id: 6,
    name: "Gemini AI Clone",
    type: "2025",
    project: "View Github",
    label: "HTML CSS JS",
    github: "https://github.com/milanlizriadi/gemini-clone",
  },
];
